### ISSUE TITLE
Monitored Lidarr albums are not synced

### ISSUE THREAD

**Issue by FricoRico** [DorskFR/tidalidarr#2]
Thank you for your continued efforts in building this tool. It seems I am unable to sync my monitored albums with Tidalidarr. The albums are never added to the queue.

Is there something I might be missing?

**Comment by DorskFR** [comment]
Thank you for raising this issue.
The logs should be providing you with context on what is happening.

At the current time, the search logic is very basic/limited:
- Only albums
- Only top hits

Therefore, this is what happens:
- Collect from lidarr the artist and title https://github.com/DorskFR/tidalidarr/blob/b62fac5a7cb3380d3d89d727a370b29bcc65d627/tidalidarr/lidarr/client.py#L74
- Search Tidal with this string and if we do not find an exact match (artist, album, top_hit) then we skip https://github.com/DorskFR/tidalidarr/blob/b62fac5a7cb3380d3d89d727a370b29bcc65d627/tidalidarr/tidal/client.py#L66

Main goal was to avoid downloading random things from the Tidal search result.

It is not ideal but until I spend time to refine this logic, there is the option to add manually with the `album_id`.
https://github.com/DorskFR/tidalidarr?tab=readme-ov-file#manually-adding-albums

If however it downloads a few albums and then sleeps forever, there might be an actual bug, I will look into it.

**Comment by DorskFR** [comment]
I added an endpoint with more information and found a bug on the lidarr processing loop, that might have been your issue.

Feel free to test with `1.28.0` if it improves things.

**Comment by DorskFR** [comment]
Closing this, feel free to reopen if you still encounter the issue!
